apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cosign.sigstore.dev/verified: "true"
    cosign.sigstore.dev/signed-at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  labels:
    app: vote
  name: vote
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      containers:
      - image: hw-harbor.bluesunnywings.com/sysdig-poc/vote:v2-7dfff6d18ac74641b0d5df68467127cf083034d2
        name: vote
        ports:
        - containerPort: 80
          name: vote
