name: Cleanup and Rebuild (Docker v2)

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to rebuild (vote, worker, result, or all)'
        required: true
        default: 'all'
        type: choice
        options:
        - vote
        - worker  
        - result
        - all

env:
  HARBOR_REGISTRY: hw-harbor.bluesunnywings.com
  HARBOR_PROJECT: sysdig-poc

jobs:
  cleanup-and-rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        
      - name: Harbor Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Vote Service (Docker v2)
        if: github.event.inputs.service == 'vote' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/vote:latest
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/vote:main-v2
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/vote:${{ github.sha }}
          target: final
          provenance: false
          sbom: false
          outputs: type=image,oci-mediatypes=false

      - name: Build Worker Service (Docker v2)
        if: github.event.inputs.service == 'worker' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/worker:latest
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/worker:main-v2
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/worker:${{ github.sha }}
          provenance: false
          sbom: false
          outputs: type=image,oci-mediatypes=false

      - name: Build Result Service (Docker v2)
        if: github.event.inputs.service == 'result' || github.event.inputs.service == 'all'
        uses: docker/build-push-action@v6
        with:
          context: ./result
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/result:latest
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/result:main-v2
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/result:${{ github.sha }}
          provenance: false
          sbom: false
          outputs: type=image,oci-mediatypes=false

      - name: Verify Docker v2 Format
        run: |
          echo "Verifying Docker v2 manifest format..."
          docker manifest inspect ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/worker:latest | jq '.mediaType'
