name: Result Service

on:
  push:
    branches: [ main, develop ]
    paths: [ 'result/**', '.github/workflows/result.yaml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'result/**', '.github/workflows/result.yaml' ]
  workflow_dispatch:

# Prevent concurrent GitOps updates
concurrency:
  group: gitops-update
  cancel-in-progress: false

env:
  HARBOR_REGISTRY: hw-harbor.bluesunnywings.com
  HARBOR_PROJECT: sysdig-poc
  SERVICE: result

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
        
      - name: Harbor Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build for Scan
        run: docker build --platform linux/amd64 -t ${{ env.SERVICE }}-scan:${{ github.sha }} ./result
          
      - name: Security Scan
        uses: sysdiglabs/scan-action@v6
        with:
          image-tag: ${{ env.SERVICE }}-scan:${{ github.sha }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_API_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_ENDPOINT }}
          mode: vm
          severity-at-least: medium
          stop-on-failed-policy-eval: false

      - name: Push to Harbor (Docker v2 Compatible)
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: ./result
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.SERVICE }}:v2-latest
            ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.SERVICE }}:v2-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          sbom: false
          outputs: type=image,oci-mediatypes=false

      - name: Update GitOps Manifest
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        run: |
          # Configure git
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Update image tag in manifest
          sed -i "s|image: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.SERVICE }}:.*|image: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.SERVICE }}:v2-${{ github.sha }}|g" manifests/result/deployment.yaml
          
          # Check if there are changes to commit
          if git diff --quiet manifests/result/deployment.yaml; then
            echo "No changes to commit"
            exit 0
          fi
          
          # Commit changes
          git add manifests/result/deployment.yaml
          git commit -m "🚀 Update ${{ env.SERVICE }} image to v2-${{ github.sha }}"
          
          # Push with simple retry and pull logic
          for i in {1..5}; do
            echo "Push attempt $i/5"
            
            if git push origin HEAD:main; then
              echo "✅ Successfully pushed changes"
              break
            else
              echo "❌ Push failed, pulling latest changes..."
              
              # Pull latest changes and rebase
              git pull --rebase origin main
              
              # If there are conflicts, our change should win (it's just one line)
              if [ $? -ne 0 ]; then
                echo "🔧 Resolving conflicts..."
                git checkout --ours manifests/result/deployment.yaml
                git add manifests/result/deployment.yaml
                git rebase --continue
              fi
              
              if [ $i -eq 5 ]; then
                echo "❌ Failed to push after 5 attempts"
                exit 1
              fi
              
              # Wait before retry (exponential backoff)
              sleep $((i * 3))
            fi
          done

      - name: Upload SARIF
        if: always() && hashFiles('sarif.json') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif.json

      - name: Archive Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE }}-scan-${{ github.sha }}
          path: |
            sarif.json
            scan-result.json
          if-no-files-found: ignore
